using DirectoryService.Application.Abstractions;
using DirectoryService.Contracts.Departments;

namespace DirectoryService.Application.Departments.Update.DepartmentsLocations;

public record UpdateDepartmentsLocationsCommand(UpdateDepartmentsLocationsRequest Request) : ICommand;